ci: enable doc tests
hyperledger-iroha/iroha pull request #5201
Opened 2024-10-29 14:09 UTC by s8sato

## Context

Doc tests are disabled by default [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov?tab=readme-ov-file#known-limitations)

### Solution

Enable it

### Checklist

- [x] I've read [`CONTRIBUTING.md`](../CONTRIBUTING.md).
- [ ] All review comments have been resolved.
- [ ] All CI checks pass.

2024-10-31 06:56 UTC, 0x009922 submitted a review, later dismissed

2024-10-31 06:56 UTC, 0x009922 commented on .github/workflows/iroha2-dev-pr.yml
Running doctests with only `--all-features` seems sufficient to me. Or is it not?

2024-11-01 04:10 UTC, s8sato commented on .github/workflows/iroha2-dev-pr.yml
Agreed, what doc tests should ensure would be that they are not false code, not that they works under any features set

2024-11-05 03:59 UTC, 0x009922 submitted a review, later dismissed

2024-11-05 05:16 UTC, s8sato commented
Converted to draft as @mversic has another solution to the failing doc test, and I'd wait for his PR and rebase it

2024-11-06 11:56 UTC, mversic commented on crates/iroha_telemetry_derive/Cargo.toml
> +
remove this

2024-11-06 11:56 UTC, mversic requested changes

2024-11-06 11:56 UTC, mversic commented on crates/iroha_telemetry_derive/Cargo.toml
> +
remove this

2024-11-11 08:37 UTC, 0x009922 approved these changes

2024-11-11 08:37 UTC, merged